export const students = [
  {
    id: 1,
    name: "Olamide Akintan",
    email: "olamideakintan@gmail.com",
    enrolledDate: "25 Feb, 2025",
    lastActivity: "25 Feb, 2025",
    status: "Active",
    avatar:  "/studentImage.png",
  },
  
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@gmail.com",
    enrolledDate: "20 Feb, 2025",
    lastActivity: "22 Feb, 2025",
    status: "Active",
    avatar: "/studentImage.png",
  },
  {
    id: 3,
    name: "John Smith",
    email: "johnsmith@gmail.com",
    enrolledDate: "18 Feb, 2025",
    lastActivity: "21 Feb, 2025",
    status: "Active",
    avatar: "/studentImage.png",
  },
  {
    id: 4,
    name: "Mary Johnson",
    email: "maryjohnson@gmail.com",
    enrolledDate: "15 Feb, 2025",
    lastActivity: "20 Feb, 2025",
    status: "Active",
    avatar: "/studentImage.png",
  },
  {
    id: 5,
    name: "Chris Lee",
    email: "chrislee@gmail.com",
    enrolledDate: "10 Feb, 2025",
    lastActivity: "19 Feb, 2025",
    status: "Active",
    avatar: "/studentImage.png",
  },
  {
    id: 6,
    name: "Patricia Brown",
    email: "patriciabrown@gmail.com",
    enrolledDate: "05 Feb, 2025",
    lastActivity: "18 Feb, 2025",
    status: "Active",
    avatar: "/studentImage.png",
  },
];