export const feedbacks = [
  {
    id: 1,
    img: "/Avatars.jpg",
    name: "Lisa Simpson",
     email: "lisasimpson@gmail.com",
    userType: "Dojo Admin",
    feedback: "I love how easy it is to track student progress and message instructor grading reports. But I'd like more filters for attendance - that would help with planning.",
    date: "13 Jul, 2025",
    time: "8:00pm",
    status: "In-Review",
  },
  {
    id: 2,
    img: "/Avatars.jpg",
    name: "Bart Simpson",
    email: "bartsimpson@gmail.com",
    userType: "Instructor",
    feedback: "The grading system is intuitive, but notifications for new messages could be improved.",
    date: "13 Jul, 2025",
    time: "8:00pm",
    status: "Resolved",
  },
  {
    id: 3,
    img: "/Avatars.jpg",
    name: "Homer Simpson",
    email: "homersimpson@gmail.com",
    userType: "Parent",
    feedback: "I appreciate the weekly reports, but would like to see more details on attendance.",
    date: "13 Jul, 2025",
    time: "8:00pm",
    status: "In-Review",
  },
  {
    id: 4,
    img: "/Avatars.jpg",
    name: "Marge Simpson",
    email: "margesimpson@gmail.com",
    userType: "Student",
    feedback: "Messaging instructors is easy, but the mobile layout could be better.",
    date: "13 Jul, 2025",
    time: "8:00pm",
    status: "Resolved",
  },
  {
    id: 5,
    img: "/Avatars.jpg",
    name: "Maggie Simpson",
    email: "maggiesimpson@gmail.com",
    userType: "Parent",
    feedback: "I like the attendance tracking, but wish there was a calendar view.",
    date: "13 Jul, 2025",
    time: "8:00pm",
    status: "In-Review",
  },
  {
    id: 6,
    img: "/Avatars.jpg",
    name: "Nelson Muntz",
    email: "nelsonmuntz@gmail.com",
    userType: "Instructor",
    feedback: "Reports are helpful, but exporting data would be great.",
    date: "13 Jul, 2025",
    time: "8:00pm",
    status: "Resolved",
  },
  {
    id: 7,
    img: "/Avatars.jpg",
    name: "Milhouse Van Houten",
    email: "milhousevanhouten@gmail.com",
    userType: "Student",
    feedback: "I like the grading feedback, but wish for more real-time updates.",
    date: "13 Jul, 2025",
    time: "8:00pm",
    status: "In-Review",
  },
  {
    id: 8,
    img: "/Avatars.jpg",
    name: "Edna Krabappel",
    email: "ednakrabappel@gmail.com",
    userType: "Dojo Admin",
    feedback: "The dashboard is clear, but more analytics would help.",
    date: "13 Jul, 2025",
    time: "8:00pm",
    status: "Resolved",
  },
  {
    id: 9,
    img: "/Avatars.jpg",
    name: "Ralph Wiggum",
    email: "ralphwiggum@gmail.com",
    userType: "Parent",
    feedback: "Easy to use, but would like more options for messaging.",
    date: "13 Jul, 2025",
    time: "8:00pm",
    status: "In-Review",
  },
];