export const assignedClasses = [
  {
    id: 1,
    img: "/classImg.jpg",
    name: "Beginner Class",
    level: "Beginner",
    enrolled: 24,
    date: "June 30, 2024",
    status: "Active",
  },
  {
    id: 2,
    img: "/classImg.jpg",
    name: "Beginner Class",
    level: "Beginner",
    enrolled: 21,
    date: "July 10, 2024",
    status: "Active",
  },
  {
    id: 3,
    img: "/classImg.jpg",
    name: "Intermediate Class",
    level: "Intermediate",
    enrolled: 18,
    date: "June 30, 2024",
    status: "Active",
  },
  {
    id: 4,
    img: "/classImg.jpg",
    name: "Beginner Class",
    level: "Beginner",
    enrolled: 15,
    date: "June 01, 2024",
    status: "Active",
  },
  {
    id: 5,
    img: "/classImg.jpg",
    name: "Intermediate Class",
    level: "Intermediate",
    enrolled: 18,
    date: "June 30, 2024",
    status: "Active",
  },
  
];