export const attendanceSummary = {
  totalSessions: 24,
  averageRate: "75%",
  lowAttendanceCount: 5,
  lowAttendancePercent: "22%",
};

export const attendanceRows = [
  {
    id: 1,
    name: "Olamide Akintan",
    avatar: "/studentImage.png",
    attendance: "95%",
    sessionsAttended: 23,
    sessionsMissed: 1,
    lastAttended: "21 Jul, 2025",
    status: "Active",
  },
  {
    id: 2,
    name: "Jane Doe",
    avatar:  "/studentImage.png",
    attendance: "80%",
    sessionsAttended: 19,
    sessionsMissed: 5,
    lastAttended: "20 Jul, 2025",
    status: "Active",
  },
  {
    id: 3,
    name: "John Smith",
    avatar:  "/studentImage.png",
    attendance: "60%",
    sessionsAttended: 15,
    sessionsMissed: 9,
    lastAttended: "18 Jul, 2025",
    status: "Active",
  },
  {
    id: 4,
    name: "Mary Johnson",
    avatar:  "/studentImage.png",
    attendance: "50%",
    sessionsAttended: 12,
    sessionsMissed: 12,
    lastAttended: "15 Jul, 2025",
    status: "Active",
  },
  {
    id: 5,
    name: "Chris Lee",
    avatar:  "/studentImage.png",
    attendance: "40%",
    sessionsAttended: 10,
    sessionsMissed: 14,
    lastAttended: "10 Jul, 2025",
    status: "Active",
  },
  {
    id: 6,
    name: "Patricia Brown",
    avatar:  "/studentImage.png",
    attendance: "30%",
    sessionsAttended: 7,
    sessionsMissed: 17,
    lastAttended: "05 Jul, 2025",
    status: "Active",
  },
];